all:
	# g++ main-00.cpp -o a00 -O3 `sdl-config --cflags` `sdl-config --libs` -mwindows
	# g++ main-01.cpp -o a01 -O3 `sdl-config --cflags` `sdl-config --libs` -mwindows
	#g++ main-02.cpp -o a02 -O3 `sdl-config --cflags` `sdl-config --libs` -mwindows
	g++ main-03.cpp -o a03 -O3 `sdl-config --cflags` `sdl-config --libs` -mwindows

